In [1]:
import numpy as np
import pandas as pd

# Load dataset
df = pd.read_excel(r"C:\Users\KGCAS\Downloads\Trip_Analysis (1).xlsx")

# Display first 5 rows
df.head()

,Trip_Distance,Fare_Amount,Ride_Category,Surge_Multiplier,Customer_Rating,Ride_Time
0,8,270.569350,Shared,2.5,3,Non-Peak
1,21,275.161032,Economy,2.5,3,Non-Peak
2,16,359.748971,Economy,2.0,5,Non-Peak
3,12,264.044264,Premium,1.5,5,Non-Peak
4,9,225.256916,Shared,2.0,2,Non-Peak


In [2]:
# Check number of rows and columns
print("Shape:", df.shape)

# Check column names
print("\nColumns:")
print(df.columns)

# Check data types
print("\nData Types:")
print(df.dtypes)

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Check duplicate rows
print("\nDuplicate Rows:", df.duplicated().sum())

Shape: (200, 6)

Columns:
Index(['Trip_Distance', 'Fare_Amount', 'Ride_Category', 'Surge_Multiplier',
       'Customer_Rating', 'Ride_Time'],
      dtype='object')

Data Types:
Trip_Distance         int64
Fare_Amount         float64
Ride_Category        object
Surge_Multiplier    float64
Customer_Rating       int64
Ride_Time            object
dtype: object

Missing Values:
Trip_Distance       0
Fare_Amount         0
Ride_Category       0
Surge_Multiplier    0
Customer_Rating     0
Ride_Time           0
dtype: int64

Duplicate Rows: 0


In [3]:
# Remove duplicate rows
df = df.drop_duplicates()

print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0


In [4]:
# Check missing values
print(df.isnull().sum())

Trip_Distance       0
Fare_Amount         0
Ride_Category       0
Surge_Multiplier    0
Customer_Rating     0
Ride_Time           0
dtype: int64


In [5]:
# Check negative values
print("Negative Trip Distance:")
print(df[df["Trip_Distance"] < 0])

print("\nNegative Fare Amount:")
print(df[df["Fare_Amount"] < 0])

print("\nInvalid Surge Multiplier:")
print(df[df["Surge_Multiplier"] <= 0])

print("\nInvalid Customer Rating:")
print(df[(df["Customer_Rating"] < 0) | (df["Customer_Rating"] > 5)])

Negative Trip Distance:
Empty DataFrame
Columns: [Trip_Distance, Fare_Amount, Ride_Category, Surge_Multiplier, Customer_Rating, Ride_Time]
Index: []

Negative Fare Amount:
Empty DataFrame
Columns: [Trip_Distance, Fare_Amount, Ride_Category, Surge_Multiplier, Customer_Rating, Ride_Time]
Index: []

Invalid Surge Multiplier:
Empty DataFrame
Columns: [Trip_Distance, Fare_Amount, Ride_Category, Surge_Multiplier, Customer_Rating, Ride_Time]
Index: []

Invalid Customer Rating:
Empty DataFrame
Columns: [Trip_Distance, Fare_Amount, Ride_Category, Surge_Multiplier, Customer_Rating, Ride_Time]
Index: []


In [6]:
df.describe()

,Trip_Distance,Fare_Amount,Surge_Multiplier,Customer_Rating
count,200.000000,200.000000,200.000000,200.000000
mean,15.640000,260.312376,1.677500,2.930000
std,8.433625,78.706127,0.548862,1.444136
min,2.000000,37.585916,1.000000,1.000000
25%,8.000000,208.528826,1.000000,2.000000
50%,15.000000,256.907103,1.500000,3.000000
75%,23.000000,319.763782,2.000000,4.000000
max,29.000000,468.753773,2.500000,5.000000


In [7]:
print("Ride Categories:")
print(df["Ride_Category"].value_counts())

print("\nRide Time:")
print(df["Ride_Time"].value_counts())

Ride Categories:
Ride_Category
Economy    82
Shared     60
Premium    58
Name: count, dtype: int64

Ride Time:
Ride_Time
Peak        103
Non-Peak     97
Name: count, dtype: int64


In [8]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Missing values:
Trip_Distance       0
Fare_Amount         0
Ride_Category       0
Surge_Multiplier    0
Customer_Rating     0
Ride_Time           0
dtype: int64

Duplicate rows:
0


In [9]:
df = df.drop_duplicates()

df.to_excel("Cleaned_Trip_Analysis.xlsx", index=False)

print("Dataset cleaned and saved successfully!")

Dataset cleaned and saved successfully!


In [10]:
# Create vectors from the dataset

vector_a = df["Trip_Distance"].to_numpy()
vector_b = df["Fare_Amount"].to_numpy()

print("Trip Distance Vector:")
print(vector_a)

print("\nFare Amount Vector:")
print(vector_b)

Trip Distance Vector:
[ 8 21 16 12  9 22  8 27 20 24 12 12 25 22  5  9 25  4 23 22  3 25 13  7
  3 29 22  2 13 27 23 13 26 18 28 28 11 29 29 17 16 16 20 13 24 21 26  4
  6 20  8 22 10  8 19  5 26 29 15 19 27 10 27 22  3 21 29 16 29  8 13  9
 16  4 15 18  5 19  9  5  3  7 23 11  5 23 19 27 13  3 11  5 15 17 16  9
 15 24 29 26  9 22 17 14 19 16 22 25 27 26 29 29 29 14 10 16 14  2 26  8
 10 25  2 13  9 25 12 20 18  9  4  4  2 28  6 11  8 27 10 29  8 10  9 13
  3  2 17 24 24 25  6  4 13  9 23 28  4  2  4  6 16 15  4  2  6 27 24 15
  8 28 10 16 16 27 11 29 14 20  8 18 21  5  6 24  8 14 16 12  5 14  8 28
 20 23 29  3 11 14 26 22]

Fare Amount Vector:
[270.5693496  275.16103167 359.74897068 264.04426352 225.25691628
 303.85004022 229.46958538 220.57394207 351.89868961 226.64378633
  37.58591619 277.64143551 218.35868387 226.86905148 286.23490612
 236.71512733 267.19510641  88.21480534 174.55545532 362.31669909
 248.51593564 116.11963024 164.19745325 170.59310565 258.1878146
 215.39125756 197.

In [11]:
print("Vector A dimension:", vector_a.ndim)
print("Vector A size:", vector_a.size)

print("Vector B dimension:", vector_b.ndim)
print("Vector B size:", vector_b.size)

Vector A dimension: 1
Vector A size: 200
Vector B dimension: 1
Vector B size: 200


In [12]:
# Vector addition
vector_addition = vector_a + vector_b

# Vector subtraction
vector_subtraction = vector_b - vector_a

# Dot product
dot_product = np.dot(vector_a, vector_b)

print("Vector Addition:")
print(vector_addition)

print("\nVector Subtraction:")
print(vector_subtraction)

print("\nDot Product:")
print(dot_product)

Vector Addition:
[278.5693496  296.16103167 375.74897068 276.04426352 234.25691628
 325.85004022 237.46958538 247.57394207 371.89868961 250.64378633
  49.58591619 289.64143551 243.35868387 248.86905148 291.23490612
 245.71512733 292.19510641  92.21480534 197.55545532 384.31669909
 251.51593564 141.11963024 177.19745325 177.59310565 261.1878146
 244.39125756 219.26541581 252.31498435 301.22032795 256.27770842
 227.02326339 229.28014237 303.18567713 267.409588   339.3837471
 186.0165938  198.97311152 340.85126847 214.85377253 377.72125751
 378.41642447 377.38606028 199.54873452 269.15159589 234.52540142
 344.85300867 412.52839629 323.88715325 256.73154766 240.75685625
 309.92693861 174.17011707 302.90688259 184.8247255  318.64385728
 242.12500985 244.93884808 208.15901009 236.46039794 313.48974388
 360.50884887 302.11585291 386.11092195 475.1330173  227.04072337
 254.53066263 163.79668419 361.25818049 382.95174514 188.62830752
 312.41126764 356.36566376 284.10306156 321.79211461 278.9866

In [13]:
# Create a 3 x 3 matrix

matrix_a = df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier"]].head(3).to_numpy()

print("Matrix A:")
print(matrix_a)

Matrix A:
[[  8.         270.5693496    2.5       ]
 [ 21.         275.16103167   2.5       ]
 [ 16.         359.74897068   2.        ]]


In [14]:
# Create another 3 x 3 matrix

matrix_b = df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier"]].iloc[3:6].to_numpy()

print("Matrix B:")
print(matrix_b)

Matrix B:
[[ 12.         264.04426352   1.5       ]
 [  9.         225.25691628   2.        ]
 [ 22.         303.85004022   1.        ]]


In [15]:
print("Matrix A shape:", matrix_a.shape)
print("Matrix B shape:", matrix_b.shape)

Matrix A shape: (3, 3)
Matrix B shape: (3, 3)


In [16]:
matrix_addition = matrix_a + matrix_b

print("Matrix Addition:")
print(matrix_addition)

Matrix Addition:
[[ 20.         534.61361312   4.        ]
 [ 30.         500.41794795   4.5       ]
 [ 38.         663.59901091   3.        ]]


In [17]:
matrix_multiplication = np.dot(matrix_a, matrix_b)

print("Matrix Multiplication:")
print(matrix_multiplication)

Matrix Multiplication:
[[ 2586.12414644 63819.59654168   555.63869921]
 [ 2783.44928502 68286.48010981   584.32206334]
 [ 3473.74073616 85868.35206948   745.49794137]]


In [18]:
# Calculate determinant of Matrix A

det_A = np.linalg.det(matrix_a)

print("Determinant of Matrix A:", det_A)

Determinant of Matrix A: 4546.838087963126


In [19]:
# Calculate determinant of Matrix B

det_B = np.linalg.det(matrix_b)

print("Determinant of Matrix B:", det_B)

Determinant of Matrix B: 1320.7285587702827


In [20]:
det_A = np.linalg.det(matrix_a)

print("Determinant of Matrix A:", det_A)

Determinant of Matrix A: 4546.838087963126


In [21]:
# Calculate eigenvalues and eigenvectors

eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[298.1381345  -11.67030043  -1.3068024 ]

Eigenvectors:
[[ 0.50485604  0.71250882  0.00474292]
 [ 0.5351111  -0.05825997 -0.00940241]
 [ 0.67733041  0.69924027  0.99994455]]


In [22]:
# Calculate eigenvalues and eigenvectors

eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[298.1381345  -11.67030043  -1.3068024 ]

Eigenvectors:
[[ 0.50485604  0.71250882  0.00474292]
 [ 0.5351111  -0.05825997 -0.00940241]
 [ 0.67733041  0.69924027  0.99994455]]


In [23]:
# Calculate eigenvalues and eigenvectors

eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[298.1381345  -11.67030043  -1.3068024 ]

Eigenvectors:
[[ 0.50485604  0.71250882  0.00474292]
 [ 0.5351111  -0.05825997 -0.00940241]
 [ 0.67733041  0.69924027  0.99994455]]


In [24]:
# Basic probability of each ride category

ride_probability = df["Ride_Category"].value_counts(normalize=True)

print("Probability of each ride category:")
print(ride_probability)

Probability of each ride category:
Ride_Category
Economy    0.41
Shared     0.30
Premium    0.29
Name: proportion, dtype: float64


In [25]:
# Probability of Peak and Non-Peak rides

time_probability = df["Ride_Time"].value_counts(normalize=True)

print("Probability of each ride time:")
print(time_probability)

Probability of each ride time:
Ride_Time
Peak        0.515
Non-Peak    0.485
Name: proportion, dtype: float64


In [26]:
# Conditional probability: Premium given Peak

premium_peak = ((df["Ride_Category"] == "Premium") & 
                (df["Ride_Time"] == "Peak")).sum()

peak_total = (df["Ride_Time"] == "Peak").sum()

prob_premium_given_peak = premium_peak / peak_total

print("P(Premium | Peak):", prob_premium_given_peak)

P(Premium | Peak): 0.3106796116504854


In [27]:
# Bayes' theorem

surge = df["Surge_Multiplier"] > 1

premium = df["Ride_Category"] == "Premium"

P_premium = premium.mean()
P_surge = surge.mean()
P_surge_given_premium = surge[premium].mean()

P_premium_given_surge = (P_surge_given_premium * P_premium) / P_surge

print("P(Premium | Surge):", P_premium_given_surge)

P(Premium | Surge): 0.3169014084507042


In [28]:
p_economy = (df["Ride_Category"] == "Economy").mean()

print("Probability of Economy:", p_economy)

Probability of Economy: 0.41


In [29]:
from scipy.stats import binom

n = 10
k = 5

binomial_probability = binom.pmf(k, n, p_economy)

print("Probability of exactly 5 Economy rides:", binomial_probability)

Probability of exactly 5 Economy rides: 0.20872760147751476


In [30]:
from scipy.stats import norm

fare_mean = df["Fare_Amount"].mean()
fare_std = df["Fare_Amount"].std()

print("Mean Fare:", fare_mean)
print("Standard Deviation:", fare_std)

Mean Fare: 260.31237600443757
Standard Deviation: 78.70612725902723


In [31]:
prob_fare_below_300 = norm.cdf(300, fare_mean, fare_std)

print("Probability of Fare < 300:", prob_fare_below_300)

Probability of Fare < 300: 0.692957410551559


In [32]:
from scipy.stats import uniform

min_distance = df["Trip_Distance"].min()
max_distance = df["Trip_Distance"].max()

prob_distance = uniform.cdf(
    20,
    loc=min_distance,
    scale=max_distance - min_distance
)

print("Probability of Trip Distance <= 20:", prob_distance)

Probability of Trip Distance <= 20: 0.6666666666666666


In [33]:
# Mean
print("Mean:")
print(df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].mean())

# Median
print("\nMedian:")
print(df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].median())

# Mode
print("\nMode:")
print(df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].mode().iloc[0])

Mean:
Trip_Distance        15.640000
Fare_Amount         260.312376
Surge_Multiplier      1.677500
Customer_Rating       2.930000
dtype: float64

Median:
Trip_Distance        15.000000
Fare_Amount         256.907103
Surge_Multiplier      1.500000
Customer_Rating       3.000000
dtype: float64

Mode:
Trip_Distance       29.000000
Fare_Amount         37.585916
Surge_Multiplier     1.000000
Customer_Rating      1.000000
Name: 0, dtype: float64


In [34]:
# Variance
print("Variance:")
print(df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].var())

# Standard Deviation
print("\nStandard Deviation:")
print(df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].std())

Variance:
Trip_Distance         71.126030
Fare_Amount         6194.654468
Surge_Multiplier       0.301250
Customer_Rating        2.085528
dtype: float64

Standard Deviation:
Trip_Distance        8.433625
Fare_Amount         78.706127
Surge_Multiplier     0.548862
Customer_Rating      1.444136
dtype: float64


In [35]:
# Skewness
print("Skewness:")
print(df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].skew())

# Kurtosis
print("\nKurtosis:")
print(df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].kurtosis())

Skewness:
Trip_Distance       0.052817
Fare_Amount         0.022837
Surge_Multiplier    0.156067
Customer_Rating     0.062733
dtype: float64

Kurtosis:
Trip_Distance      -1.270149
Fare_Amount        -0.251430
Surge_Multiplier   -1.295399
Customer_Rating    -1.323724
dtype: float64


In [36]:
stats = pd.DataFrame({
    "Mean": df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].mean(),
    "Median": df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].median(),
    "Mode": df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].mode().iloc[0],
    "Variance": df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].var(),
    "Std_Dev": df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].std(),
    "Skewness": df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].skew(),
    "Kurtosis": df[["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]].kurtosis()
})

stats

,Mean,Median,Mode,Variance,Std_Dev,Skewness,Kurtosis
Trip_Distance,15.640000,15.000000,29.000000,71.126030,8.433625,0.052817,-1.270149
Fare_Amount,260.312376,256.907103,37.585916,6194.654468,78.706127,0.022837,-0.251430
Surge_Multiplier,1.677500,1.500000,1.000000,0.301250,0.548862,0.156067,-1.295399
Customer_Rating,2.930000,3.000000,1.000000,2.085528,1.444136,0.062733,-1.323724


In [37]:
# Calculate percentiles for Fare Amount

p25 = np.percentile(df["Fare_Amount"], 25)
p50 = np.percentile(df["Fare_Amount"], 50)
p75 = np.percentile(df["Fare_Amount"], 75)

print("25th Percentile:", p25)
print("50th Percentile:", p50)
print("75th Percentile:", p75)

25th Percentile: 208.5288261048614
50th Percentile: 256.90710336367647
75th Percentile: 319.7637824819526


In [38]:
Q1 = df["Fare_Amount"].quantile(0.25)
Q3 = df["Fare_Amount"].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: 208.5288261048614
Q3: 319.7637824819526
IQR: 111.23495637709121


In [39]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Lower Bound: 41.67639153922457
Upper Bound: 486.61621704758943


In [40]:
iqr_outliers = df[
    (df["Fare_Amount"] < lower_bound) |
    (df["Fare_Amount"] > upper_bound)
]

print("Number of IQR Outliers:", len(iqr_outliers))

print("\nOutlier Fare Values:")
print(iqr_outliers["Fare_Amount"])

Number of IQR Outliers: 1

Outlier Fare Values:
10    37.585916
Name: Fare_Amount, dtype: float64


In [41]:
from scipy.stats import zscore

df["Fare_Zscore"] = zscore(df["Fare_Amount"])

z_outliers = df[abs(df["Fare_Zscore"]) > 3]

print("Number of Z-score Outliers:", len(z_outliers))

print("\nZ-score Outliers:")
print(z_outliers[["Fare_Amount", "Fare_Zscore"]])

Number of Z-score Outliers: 0

Z-score Outliers:
Empty DataFrame
Columns: [Fare_Amount, Fare_Zscore]
Index: []


In [42]:
num_cols = ["Trip_Distance", "Fare_Amount", "Surge_Multiplier", "Customer_Rating"]

pearson_corr = df[num_cols].corr(method="pearson")

print("Pearson Correlation:")
print(pearson_corr)

Pearson Correlation:
                  Trip_Distance  Fare_Amount  Surge_Multiplier  \
Trip_Distance          1.000000     0.016813          0.017131   
Fare_Amount            0.016813     1.000000          0.017419   
Surge_Multiplier       0.017131     0.017419          1.000000   
Customer_Rating       -0.084599     0.052723         -0.041304   

                  Customer_Rating  
Trip_Distance           -0.084599  
Fare_Amount              0.052723  
Surge_Multiplier        -0.041304  
Customer_Rating          1.000000  


In [43]:
spearman_corr = df[num_cols].corr(method="spearman")

print("Spearman Correlation:")
print(spearman_corr)

Spearman Correlation:
                  Trip_Distance  Fare_Amount  Surge_Multiplier  \
Trip_Distance          1.000000     0.023427          0.025459   
Fare_Amount            0.023427     1.000000          0.011764   
Surge_Multiplier       0.025459     0.011764          1.000000   
Customer_Rating       -0.082067     0.047499         -0.047091   

                  Customer_Rating  
Trip_Distance           -0.082067  
Fare_Amount              0.047499  
Surge_Multiplier        -0.047091  
Customer_Rating          1.000000  


In [44]:
covariance = df[num_cols].cov()

print("Covariance:")
print(covariance)

Covariance:
                  Trip_Distance  Fare_Amount  Surge_Multiplier  \
Trip_Distance         71.126030    11.160173          0.079296   
Fare_Amount           11.160173  6194.654468          0.752497   
Surge_Multiplier       0.079296     0.752497          0.301250   
Customer_Rating       -1.030352     5.992595         -0.032739   

                  Customer_Rating  
Trip_Distance           -1.030352  
Fare_Amount              5.992595  
Surge_Multiplier        -0.032739  
Customer_Rating          2.085528  


In [45]:
corr_matrix = df[num_cols].corr()

print("Correlation Matrix:")
print(corr_matrix)

print("\nTrip Distance vs Fare Amount:")
print(corr_matrix.loc["Trip_Distance", "Fare_Amount"])

Correlation Matrix:
                  Trip_Distance  Fare_Amount  Surge_Multiplier  \
Trip_Distance          1.000000     0.016813          0.017131   
Fare_Amount            0.016813     1.000000          0.017419   
Surge_Multiplier       0.017131     0.017419          1.000000   
Customer_Rating       -0.084599     0.052723         -0.041304   

                  Customer_Rating  
Trip_Distance           -0.084599  
Fare_Amount              0.052723  
Surge_Multiplier        -0.041304  
Customer_Rating          1.000000  

Trip Distance vs Fare Amount:
0.016813110993310877


In [46]:
df["Trip_Distance"].corr(df["Fare_Amount"])

np.float64(0.016813110993310912)

In [47]:
fare_mean = df["Fare_Amount"].mean()

print("Estimated Mean Fare:", fare_mean)

Estimated Mean Fare: 260.31237600443757


In [48]:
import numpy as np

fare = df["Fare_Amount"].to_numpy()

bootstrap_means = []

for i in range(1000):
    sample = np.random.choice(fare, size=len(fare), replace=True)
    bootstrap_means.append(sample.mean())

print("Bootstrap Mean:", np.mean(bootstrap_means))

Bootstrap Mean: 260.2391768158449


In [49]:
lower = np.percentile(bootstrap_means, 2.5)
upper = np.percentile(bootstrap_means, 97.5)

print("95% Confidence Interval:")
print("Lower:", lower)
print("Upper:", upper)

95% Confidence Interval:
Lower: 249.3569648749101
Upper: 270.70270761231285


In [50]:
sample_means = []

for i in range(1000):
    sample = np.random.choice(fare, size=30, replace=True)
    sample_means.append(sample.mean())

print("Mean of Sample Means:", np.mean(sample_means))
print("Standard Deviation of Sample Means:", np.std(sample_means))

Mean of Sample Means: 260.14991711410966
Standard Deviation of Sample Means: 14.318990852617649


In [51]:
from scipy.stats import ttest_ind

premium_fare = df[df["Ride_Category"] == "Premium"]["Fare_Amount"]
economy_fare = df[df["Ride_Category"] == "Economy"]["Fare_Amount"]

t_stat, p_value = ttest_ind(premium_fare, economy_fare, equal_var=False)

print("T-Statistic:", t_stat)
print("P-Value:", p_value)

T-Statistic: -0.40600606266641986
P-Value: 0.6854530831483114


In [52]:
from scipy.stats import chi2_contingency

table = pd.crosstab(df["Ride_Category"], df["Ride_Time"])

chi2, p_value, dof, expected = chi2_contingency(table)

print("Chi-Square Statistic:", chi2)
print("P-Value:", p_value)

Chi-Square Statistic: 1.4810469877052506
P-Value: 0.4768642146833866


In [53]:
from scipy.stats import f

premium_var = premium_fare.var()
economy_var = economy_fare.var()

F = premium_var / economy_var

df1 = len(premium_fare) - 1
df2 = len(economy_fare) - 1

p_value = 2 * min(
    f.cdf(F, df1, df2),
    1 - f.cdf(F, df1, df2)
)

print("F-Statistic:", F)
print("P-Value:", p_value)

F-Statistic: 1.0405395155977981
P-Value: 0.8600388216850483


In [54]:
print(df["Ride_Category"].unique())

['Shared' 'Economy' 'Premium']


In [55]:
from scipy.stats import f_oneway

groups = [
    group["Fare_Amount"].values
    for name, group in df.groupby("Ride_Category")
]

F_stat, p_value = f_oneway(*groups)

print("ANOVA F-Statistic:", F_stat)
print("P-Value:", p_value)

ANOVA F-Statistic: 0.9284988792342406
P-Value: 0.3968686165946833


In [56]:
peak_fare = df[df["Ride_Time"] == "Peak"]["Fare_Amount"]
non_peak_fare = df[df["Ride_Time"] != "Peak"]["Fare_Amount"]

t_stat, p_value = ttest_ind(
    peak_fare,
    non_peak_fare,
    equal_var=False
)

print("T-Statistic:", t_stat)
print("P-Value:", p_value)

T-Statistic: -0.596491792388811
P-Value: 0.5515482990013166


In [57]:
from scipy.stats import pearsonr

r, p_value = pearsonr(df["Trip_Distance"], df["Fare_Amount"])

print("Pearson Correlation:", r)
print("P-Value:", p_value)

Pearson Correlation: 0.016813110993310947
P-Value: 0.8132001771984588


In [58]:
premium = df[df["Ride_Category"] == "Premium"]["Fare_Amount"]
economy = df[df["Ride_Category"] == "Economy"]["Fare_Amount"]

print("Premium Mean:", premium.mean())
print("Economy Mean:", economy.mean())

t_stat, p_value = ttest_ind(premium, economy, equal_var=False)

print("T-Statistic:", t_stat)
print("P-Value:", p_value)

Premium Mean: 252.45503727502648
Economy Mean: 257.74844283796944
T-Statistic: -0.40600606266641986
P-Value: 0.6854530831483114


In [59]:
from scipy.stats import spearmanr

rho, p_value = spearmanr(
    df["Surge_Multiplier"],
    df["Customer_Rating"]
)

print("Spearman Correlation:", rho)
print("P-Value:", p_value)

Spearman Correlation: -0.04709083768799108
P-Value: 0.5078698477562074


In [60]:
peak = df[df["Ride_Time"] == "Peak"]["Fare_Amount"]
non_peak = df[df["Ride_Time"] != "Peak"]["Fare_Amount"]

print("Peak Mean Fare:", peak.mean())
print("Non-Peak Mean Fare:", non_peak.mean())

t_stat, p_value = ttest_ind(peak, non_peak, equal_var=False)

print("T-Statistic:", t_stat)
print("P-Value:", p_value)

Peak Mean Fare: 257.0746665038188
Non-Peak Mean Fare: 263.75035619581627
T-Statistic: -0.596491792388811
P-Value: 0.5515482990013166


In [61]:
Q1 = df["Fare_Amount"].quantile(0.25)
Q3 = df["Fare_Amount"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Fare_Amount"] < lower) |
    (df["Fare_Amount"] > upper)
]

print("Lower Bound:", lower)
print("Upper Bound:", upper)
print("Number of Outliers:", len(outliers))

Lower Bound: 41.67639153922457
Upper Bound: 486.61621704758943
Number of Outliers: 1


In [62]:
category_probability = df["Ride_Category"].value_counts(normalize=True)

print("Ride Category Probabilities:")
print(category_probability)

Ride Category Probabilities:
Ride_Category
Economy    0.41
Shared     0.30
Premium    0.29
Name: proportion, dtype: float64


In [63]:
conditional_probability = pd.crosstab(
    df["Ride_Time"],
    df["Ride_Category"],
    normalize="index"
)

print(conditional_probability)

Ride_Category   Economy   Premium    Shared
Ride_Time                                  
Non-Peak       0.391753  0.268041  0.340206
Peak           0.427184  0.310680  0.262136


In [64]:
factors = [
    "Trip_Distance",
    "Surge_Multiplier",
    "Customer_Rating"
]

relationship = df[factors + ["Fare_Amount"]].corr()

print(relationship["Fare_Amount"].sort_values(ascending=False))

Fare_Amount         1.000000
Customer_Rating     0.052723
Surge_Multiplier    0.017419
Trip_Distance       0.016813
Name: Fare_Amount, dtype: float64


Conclusion

The Smart Mobility & Ride Analytics project analyzed ride-hailing data using NumPy, Pandas, probability, statistics, and hypothesis testing. The analysis helped understand trip distance, fare amount, surge pricing, customer ratings, and ride patterns. Correlation analysis showed only weak relationships between fare amount and the selected factors. Overall, the project demonstrates how statistical and mathematical methods can support data-driven analysis of ride-hailing operations.